### ISSUE TITLE
Añadir Topic de cursada

### ISSUE THREAD

**Issue by juli-rivero** [nehuencabibbo/IS1#1]
Buenas, estoy trabajando con una página que es muy parecida a FIUBA-Repos, solo que tambien lo podes clasificar por cursos ademas que por materias.

Veo que trabajaste con la cátedra Leveroni, si querés le podes agregar el id del curso asi apareces

En el apartado de [Ingeniería de Software I](https://juli-rivero.github.io/FIUBA-Share/#/ingenieria-de-software-i/) están los cursos, entras al curso de Leveroni en el cual trabajaste y le copias el topic. Si lo pegas en el repo y refrescas la página vas a poder ver tu repo

> [!TIP]
> Si agregas los filtros y les copias los topics de estos vas a aparecer aun con los filtros :1st_place_medal: 

Esos topics son los ids que los obtuve del SIU Guaraní - oferta de comisiones, asi que todo oficial :+1:  (excepto por los filtros de actividades que ahí sí me los inventé yo :-1: )

Es algo nueva, pero con el tiempo se va a ir llenando de repositorios :100:

**Comment by nehuencabibbo** [comment]
Listo, suerte con tu proyecto :+1:
